# Deployment Target
platform :ios, '12.0'
install! 'cocoapods', :warn_for_unused_master_specs_repo => false

# Add pods as frameworks so we could add obj-c and swift 3.0 pods
use_frameworks!

target 'ViewState_Example' do
  # Development
  pod 'ViewState/RxSwift', :path => '../'
  
  # Mine
  pod 'APExtensions', :git => 'https://github.com/APUtils/APExtensions', :branch => 'master'
end

post_install do |installer|
  # Add podInstall.command and podUpdate.command shell scripts to Pods project
  pods_project = installer.pods_project
  pods_project.new_file "../Scripts/Cocoapods/podInstall.command"
  pods_project.new_file "../Scripts/Cocoapods/podUpdate.command"
  
  # Silence Pods project warning
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['DEAD_CODE_STRIPPING'] = 'YES'
  end
  
  # Update specific target build configurations
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Silence deployment target warnings
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings.delete 'ARCHS'
    end
  end
end
